service: postgres-s3-lambda-backup-python

provider:
  name: aws
  runtime: python3.7
  region: us-east-2
  versionFunctions: false

functions:
  main:
    handler: handler.main
    memorySize: 128
    events:
    #  - http:
    #      path: /
    #      method: get
    #  - schedule: rate(10 minutes)
      - schedule: rate(2 days)

package:
  exclude:
    - myssh.pem
    - dev_secrets.py
    - .env

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true